<?
	//include module
	\Bitrix\Main\Loader::includeModule("dw.deluxe");

	//vars
	$catalogIblockId = null;
	$arPriceCodes = array();

	//get template settings
	$arTemplateSettings = DwSettings::getInstance()->getCurrentSettings();
	if(!empty($arTemplateSettings)){
		$catalogIblockId = $arTemplateSettings["TEMPLATE_PRODUCT_IBLOCK_ID"];
		$arPriceCodes = explode(", ", $arTemplateSettings["TEMPLATE_PRICE_CODES"]);
	}
?>
<?$APPLICATION->IncludeComponent(
	"dresscode:search.line", 
	"version2", 
	array(
		"COMPONENT_TEMPLATE" => "version2",
		"IBLOCK_TYPE" => "1c_catalog",
		"IBLOCK_ID" => "21",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		"PRICE_CODE" => array(
			0 => "Розничные",
		),
		"CONVERT_CURRENCY" => "N",
		"CURRENCY_ID" => "RUB",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "COLOR",
			2 => "ZOOM2",
			3 => "BATTERY_LIFE",
			4 => "SWITCH",
			5 => "GRAF_PROC",
			6 => "LENGTH_OF_CORD",
			7 => "DISPLAY",
			8 => "LOADING_LAUNDRY",
			9 => "FULL_HD_VIDEO_RECORD",
			10 => "INTERFACE",
			11 => "COMPRESSORS",
			12 => "Number_of_Outlets",
			13 => "MAX_RESOLUTION_VIDEO",
			14 => "MAX_BUS_FREQUENCY",
			15 => "MAX_RESOLUTION",
			16 => "FREEZER",
			17 => "POWER_SUB",
			18 => "POWER",
			19 => "HARD_DRIVE_SPACE",
			20 => "MEMORY",
			21 => "OS",
			22 => "ZOOM",
			23 => "PAPER_FEED",
			24 => "SUPPORTED_STANDARTS",
			25 => "VIDEO_FORMAT",
			26 => "SUPPORT_2SIM",
			27 => "MP3",
			28 => "ETHERNET_PORTS",
			29 => "MATRIX",
			30 => "CAMERA",
			31 => "PHOTOSENSITIVITY",
			32 => "DEFROST",
			33 => "SPEED_WIFI",
			34 => "SPIN_SPEED",
			35 => "PRINT_SPEED",
			36 => "SOCKET",
			37 => "IMAGE_STABILIZER",
			38 => "GSM",
			39 => "SIM",
			40 => "TYPE",
			41 => "MEMORY_CARD",
			42 => "TYPE_BODY",
			43 => "TYPE_MOUSE",
			44 => "TYPE_PRINT",
			45 => "CONNECTION",
			46 => "TYPE_OF_CONTROL",
			47 => "TYPE_DISPLAY",
			48 => "TYPE2",
			49 => "REFRESH_RATE",
			50 => "RANGE",
			51 => "AMOUNT_MEMORY",
			52 => "MEMORY_CAPACITY",
			53 => "VIDEO_BRAND",
			54 => "DIAGONAL",
			55 => "RESOLUTION",
			56 => "TOUCH",
			57 => "CORES",
			58 => "LINE_PROC",
			59 => "PROCESSOR",
			60 => "CLOCK_SPEED",
			61 => "TYPE_PROCESSOR",
			62 => "PROCESSOR_SPEED",
			63 => "HARD_DRIVE",
			64 => "HARD_DRIVE_TYPE",
			65 => "Number_of_memory_slots",
			66 => "MAXIMUM_MEMORY_FREQUENCY",
			67 => "TYPE_MEMORY",
			68 => "BLUETOOTH",
			69 => "FM",
			70 => "GPS",
			71 => "HDMI",
			72 => "SMART_TV",
			73 => "USB",
			74 => "WIFI",
			75 => "FLASH",
			76 => "ROTARY_DISPLAY",
			77 => "SUPPORT_3D",
			78 => "SUPPORT_3G",
			79 => "WITH_COOLER",
			80 => "FINGERPRINT",
			81 => "PROFILE",
			82 => "GAS_CONTROL",
			83 => "GRILL",
			84 => "GENRE",
			85 => "INTAKE_POWER",
			86 => "SURFACE_COATING",
			87 => "brand_tyres",
			88 => "SEASONOST",
			89 => "DUST_COLLECTION",
			90 => "DRYING",
			91 => "REMOVABLE_TOP_COVER",
			92 => "CONTROL",
			93 => "FINE_FILTER",
			94 => "FORM_FAKTOR",
			95 => "",
		),
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_MEASURES" => "N",
		"CONVERT_CASE" => "N",
		"STEMMING" => "N",
		"LAZY_LOAD_PICTURES" => "N"
	),
	false
);?>